// <auto-generated />
using System;
using ColdFishWMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColdFishWMS.Migrations
{
    [DbContext(typeof(ColdFishDbContext))]
    [Migration("20251212185941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ColdFishWMS.Models.Entities.CanhBao", b =>
                {
                    b.Property<int>("MaCanhBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCanhBao"));

                    b.Property<bool>("DaXuLy")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiCanhBao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLoHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MucDo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("MaCanhBao");

                    b.HasIndex("MaLoHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("CanhBao");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaLoHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaLoHang");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietPhieuNhap");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ChiTietPhieuXuat", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaLoHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhieuXuat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaLoHang");

                    b.HasIndex("MaPhieuXuat");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiTietPhieuXuat");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.DonViTinh", b =>
                {
                    b.Property<int>("MaDonViTinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonViTinh"));

                    b.Property<string>("TenDonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonViTinh");

                    b.ToTable("DonViTinh");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.KhachHang", b =>
                {
                    b.Property<string>("MaKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhachHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.LoHang", b =>
                {
                    b.Property<string>("MaLoHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaSanPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaViTri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgaySanXuat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoLuongNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoLuongTon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaLoHang");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaViTri");

                    b.ToTable("LoHang");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.LoaiSanPham", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLanSai")
                        .HasColumnType("int");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("MaVaiTro");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DaDuyet")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("MaNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuNhap");

                    b.HasIndex("MaNguoiTao");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("PhieuNhap");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuXuat", b =>
                {
                    b.Property<string>("MaPhieuXuat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DaXuat")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MaKhachHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiTao")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhieuXuat");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaNguoiTao");

                    b.ToTable("PhieuXuat");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.SanPham", b =>
                {
                    b.Property<string>("MaSanPham")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DinhMucTonThap")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaNhapMacDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDonViTinh")
                        .HasColumnType("int");

                    b.Property<int?>("MaLoai")
                        .HasColumnType("int");

                    b.Property<string>("MaNhaCungCap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<double>("NhietDoToiDa")
                        .HasColumnType("float");

                    b.Property<double>("NhietDoToiThieu")
                        .HasColumnType("float");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .HasColumnType("bit");

                    b.HasKey("MaSanPham");

                    b.HasIndex("MaDonViTinh");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNhaCungCap");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ViTriKho", b =>
                {
                    b.Property<string>("MaViTri")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ke")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Khu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenViTri")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThaiTrong")
                        .HasColumnType("bit");

                    b.HasKey("MaViTri");

                    b.ToTable("ViTriKho");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.CanhBao", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.LoHang", "LoHang")
                        .WithMany()
                        .HasForeignKey("MaLoHang");

                    b.HasOne("ColdFishWMS.Models.Entities.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham");

                    b.Navigation("LoHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ChiTietPhieuNhap", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.LoHang", "LoHang")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaLoHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.PhieuNhap", "PhieuNhap")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuNhaps")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoHang");

                    b.Navigation("PhieuNhap");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ChiTietPhieuXuat", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.LoHang", "LoHang")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaLoHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.PhieuXuat", "PhieuXuat")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaPhieuXuat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.SanPham", "SanPham")
                        .WithMany("ChiTietPhieuXuats")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoHang");

                    b.Navigation("PhieuXuat");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.LoHang", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.SanPham", "SanPham")
                        .WithMany("LoHangs")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.ViTriKho", "ViTriKho")
                        .WithMany("LoHangs")
                        .HasForeignKey("MaViTri");

                    b.Navigation("SanPham");

                    b.Navigation("ViTriKho");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.NguoiDung", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuNhap", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MaNhaCungCap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuXuat", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.KhachHang", "KhachHang")
                        .WithMany("PhieuXuats")
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("MaNguoiTao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.SanPham", b =>
                {
                    b.HasOne("ColdFishWMS.Models.Entities.DonViTinh", "DonViTinh")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDonViTinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ColdFishWMS.Models.Entities.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("MaLoai");

                    b.HasOne("ColdFishWMS.Models.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("MaNhaCungCap");

                    b.Navigation("DonViTinh");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.DonViTinh", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.KhachHang", b =>
                {
                    b.Navigation("PhieuXuats");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.LoHang", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.NhaCungCap", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuNhap", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.PhieuXuat", b =>
                {
                    b.Navigation("ChiTietPhieuXuats");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.SanPham", b =>
                {
                    b.Navigation("ChiTietPhieuNhaps");

                    b.Navigation("ChiTietPhieuXuats");

                    b.Navigation("LoHangs");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("ColdFishWMS.Models.Entities.ViTriKho", b =>
                {
                    b.Navigation("LoHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
